### PR TITLE
Truncate secrets greater than 72 chars in hash_secret

### LINKED ISSUE #225: InvalidHash on Ubuntu 20.04
On Ubuntu 20.04 using ruby 2.6.5, the following error is thrown at 512 characters (fewer characters works fine):
```
irb(main):004:0> BCrypt::Password.create("a"*512)
Traceback (most recent call last):
        7: from /home/jwcooper/.asdf/installs/ruby/2.6.5/bin/irb:23:in `<main>'
        6: from /home/jwcooper/.asdf/installs/ruby/2.6.5/bin/irb:23:in `load'
        5: from /home/jwcooper/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/irb-1.0.0/exe/irb:11:in `<top (required)>'
        4: from (irb):4
        3: from /home/jwcooper/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/bcrypt-3.1.13/lib/bcrypt/password.rb:46:in `create'
        2: from /home/jwcooper/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/bcrypt-3.1.13/lib/bcrypt/password.rb:46:in `new'
        1: from /home/jwcooper/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/bcrypt-3.1.13/lib/bcrypt/password.rb:60:in `initialize'
BCrypt::Errors::InvalidHash (invalid hash)

```
Let me know if I can provide any further information. This isn't happening on Ubuntu 18.04 or any other distributions I've tested it on.

### PR DESCRIPTION
**Pull request by asavageiv**
Fixes #225

### CODE REVIEW

**Review by tjschuck — CHANGES_REQUESTED** [review]
Thanks for this PR!  One technical issue, though: bcrypt truncates secrets at 72 _bytes_, not characters, so this probably isn't correct outside of the 1-byte character space.

**Comment by asavageiv** [comment]
Great catch! Updated to truncate based on bytesize instead and added a test for that.

File: spec/bcrypt/password_spec.rb [hunk 1]
```diff
@@ -26,6 +27,28 @@
     expect { BCrypt::Password.create( ""         ) }.not_to raise_error
     expect { BCrypt::Password.create( String.new ) }.not_to raise_error
   end
+
+  context 'with a 256 character password' do
+    before :each do
+      @secret = SecureRandom.hex(256)
```
Comment (tjschuck) [inline spec/bcrypt/password_spec.rb:33]:
```suggestion
      @secret = SecureRandom.hex(128)
```

The character string returned from SecureRandom.hex is actually 2n characters long, per the docs:

> The argument n specifies the length, in bytes, of the random number to be generated. The length of the resulting hexadecimal string is twice of n.

Comment (tjschuck) [reply spec/bcrypt/password_spec.rb:33]: Aside from that, though, what's the value of these tests?  Just that they red/green the InvalidHash error on Ubuntu 20?  It feels like they should be more explicit if that's the goal.

**Review by tjschuck — CHANGES_REQUESTED** [review]

File: spec/bcrypt/password_spec.rb (hunk 1 above)
Comment (asavageiv) [reply spec/bcrypt/password_spec.rb]: I wrote those before I wrote the specs in engine_spec and just left them. Removed them in favor of a more generic "long secret" test in the same style as the rest of the tests in the file. This would reveal the error on Ubuntu 20/Debian 11, but is generic enough to be sane on any platform. PTAL

**Comment by asavageiv** [comment]
friendly ping
